version: "3.8"

services:
  web:
    build: ./web
    ports:
      - 8080:80

  db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: api
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: mysql -u root -h 127.0.0.1 -e '\q' || exit 1
      interval: 10s
      timeout: 1s
      retries: 5
      start_period: 15s

  db_seeder:
    build: ./database 
    depends_on:
      db:
        condition: service_healthy


# Volume to hold history/legacy data 
volumes:
  api:

